#pragma once

using namespace ATL;

template <class T>
class CProxy_IBlueprintEvents : public IConnectionPointImpl<T, &__uuidof(_IBlueprintEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
