// SRATL4.idl : IDL source for SRATL4
//

// This file will be processed by the MIDL tool to
// produce the type library (SRATL4.tlb) and marshalling code.

#include "olectl.h"
import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(AB6F03E9-3213-4D29-8E8E-691D22B696FF),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IBlueprint : IDispatch{
	[propget, id(1), helpstring("Минимальное значение интервала")] HRESULT Min([out, retval] SHORT* pVal);
	[propput, id(1), helpstring("Минимальное значение интервала")] HRESULT Min([in] SHORT newVal);
	[propget, id(2), helpstring("Максимальное значение интервала")] HRESULT Max([out, retval] SHORT* pVal);
	[propput, id(2), helpstring("Максимальное значение интервала")] HRESULT Max([in] SHORT newVal);
	[propget, id(3), helpstring("Цвет фона")] HRESULT BackgroundColor([out, retval] OLE_COLOR* pVal);
	[propput, id(3), helpstring("Цвет фона")] HRESULT BackgroundColor([in] OLE_COLOR newVal);
	[propget, id(4), helpstring("Цвет линий")] HRESULT LineColor([out, retval] OLE_COLOR* pVal);
	[propput, id(4), helpstring("Цвет линий")] HRESULT LineColor([in] OLE_COLOR newVal);
	[propget, id(5), helpstring("Количество кликов")] HRESULT ClickCount([out, retval] SHORT* pVal);
	[propput, id(5), helpstring("Количество кликов")] HRESULT ClickCount([in] SHORT newVal);
};

[
	uuid(A68DEEE3-ECE1-437F-83EC-EFB49302A0CC),
	version(1.0),
]
library SRATL4Lib
{
	importlib("stdole2.tlb");
	[
		uuid(8C76200B-D12A-49FA-8AB4-93926E5F0B9C)		
	]
	dispinterface _IBlueprintEvents
	{
		properties:
		methods:
			[id(1), helpstring("Левый клик")] HRESULT LeftClick([in] LONG x,[in] LONG y);
			[id(2), helpstring("Правый клик")] HRESULT RightClick([in] LONG x, LONG y);
	};
	[
		uuid(FBF027E5-7A62-4649-AC9C-FC0C8D4EC0EE),		
		control
	]
	coclass Blueprint
	{
		[default] interface IBlueprint;
		[default, source] dispinterface _IBlueprintEvents;
	};
};

